title: "Julie's Blog"
author: Julie Kim
email: ykim2@ebnet.org
description: "Hello! Welcome to my website!"
# social links
twitter_username: duldnjs # DO NOT include the @ character, or else the build will fail!
github_username: juliekim1 # DO NOT include the @ character, or else the build will fail!
instagram_username: __juliekim

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
